Fix runtime error and update client.
Apollo-Core/EE-Deploy pull request #1
Opened 2021-10-26 17:53 UTC by doetlingerlukas

Add other Apollo parts (EE-Docker and edge-discovery) to deployments and update example workflow to take use of them.

There still seems to be a runtime error for some configurations, as the `ApolloServer` currently uses a separate VertX context, than the Apollo deployment itself. This leads to VertX complaining that not all instances are properly named.
This could be solved by sharing only one VertX instance.

A convenience method for running the `ApolloClient` was also added.

2021-10-27 13:48 UTC, FedorSmirnov89 requested changes
Main points:

- Adjustment of the build.gradle: Agree that we could update the project dependencies, but this would need to happen on the orga level. Would prefer to keep the build consistent between the repositories.
- Dependencies to EE-Docker and edge-discovery : In my opinion, there is no reason why these dependencies should be there. EE-Deploy is not intended as a standalone project, but rather as the library defining the classes used during deployment.
- Not sure whether the situation with a different context between client and server needs fixing, since this will be rather the rule than the exception in deployments

2021-10-27 13:48 UTC, FedorSmirnov89 commented on build.gradle
> +    implementation 'com.github.doetlingerlukas:edge-discovery:main-SNAPSHOT'
Disagree with this one. The deployment should not be dependent on the question whether you use Docker containers or local resources.

2021-10-27 13:48 UTC, FedorSmirnov89 commented on gradle/wrapper/gradle-wrapper.properties
> -distributionUrl=https\://services.gradle.org/distributions/gradle-6.8.3-bin.zip
Is there anything you cannot do with 6.8.3? (I would prefer to do dependency updates on the level of the organization, not per repository)

2021-10-27 13:48 UTC, FedorSmirnov89 commented on src/main/java/at/uibk/dps/ee/deploy/client/ApolloClient.java
> +  public static void main(final String[] args) {
Why should the client have a main which lets it execute a hard-coded request?

2021-10-27 13:48 UTC, FedorSmirnov89 commented on src/main/java/at/uibk/dps/ee/deploy/server/ApolloServer.java
> +      new TracingOptions().setFactory(VertxTracerFactory.NOOP)
This is so that it is possible to start the client in the same VertX instance right? Does this cause an error or a warning? The general use case is that you just have the server running somewhere and access its API (with anything that can formulate an HTTP request, not necessary a VertX webclient). Not sure whether we need a custom solution for the rare case where you have the client and the server in the same context.

2021-10-27 13:48 UTC, FedorSmirnov89 commented on src/test/java/at/uibk/dps/ee/deploy/FileStringConverterTest.java
> -      + "    <mapping id=\"addition_Demo--Enactment Engine (Local Machine)--demo\" source=\"addition_Demo\" target=\"Enactment Engine (Local Machine)\">\n"
Would prefer to not have the test tied to the Docker repo

2021-11-07 22:24 UTC, doetlingerlukas commented on build.gradle
> +    implementation 'com.github.doetlingerlukas:edge-discovery:main-SNAPSHOT'
Sure, this is not required if EE-Deploy is just a library.

2021-11-07 22:27 UTC, doetlingerlukas commented
Closing PR since EE-Deploy will stay a library. Implementation of the executable experiment has been moved to the [rpi-serverless](https://github.com/doetlingerlukas/rpi-serverless) repo.

2021-11-07 22:27 UTC, closed without merging